# Generated by Django 2.2.8 on 2019-12-23 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0005_auto_20191223_0828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likes',
        ),
        migrations.AlterModelOptions(
            name='imagepost',
            options={'ordering': ['posted_on']},
        ),
        migrations.AddField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
